version: '3.7'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/beerMachine
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=beerMachine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root