app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/beerMachine
    username: postgres
<<<<<<< HEAD
    password: Farmor230200
    poll-size: 30
=======
    password: root
    poll-size: 100
>>>>>>> main
